version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.15.3

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: npm run test:ci
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Add github.com to known hosts
          command: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Versioning
          command: npm version patch -m "version %s [skip ci]"
      - run:
          name: Push tag & changes to github.com
          command: git push
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
           - test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hold